In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6567, 4274, 6945, 650],
 [6567, 4274, 6945, 6899],
 [6567, 7066, 6945, 7871],
 [100, 2021, 4071, 7513, 6711],
 [100, 2021, 4071, 7513, 6707],
 [4722, 6567, 5914, 6945, 7935],
 [8283, 9003, 9394, 7513]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6567 4274 6945  650]
 [   0    0    0    0 6567 4274 6945 6899]
 [   0    0    0    0 6567 7066 6945 7871]
 [   0    0    0  100 2021 4071 7513 6711]
 [   0    0    0  100 2021 4071 7513 6707]
 [   0    0    0 4722 6567 5914 6945 7935]
 [   0    0    0    0 8283 9003 9394 7513]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/ashvin.sehgal/Python/GenAI - Udemy/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


array([[[ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.02375025,  0.03779067, -0.04327583, -0.03690758,
         -0.03633132, -0.00770945,  0.04879537, -0.01035811,
         -0.0092103 , -0.00896599],
        [-0.01270083,  0.04556414, -0.02706355, -0.01993944,
         -0.00987042,  0.0399138 ,  0.02374915,  0.03437991,
         -0.02690615, -0.03061995],
        [-0.02449276,  0.02465619,  0.04457814, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 6567, 4274, 6945,  650], dtype=int32)

In [24]:
model.predict(np.atleast_2d(embedded_docs[0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[[ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.03884325, -0.0467718 ,  0.04913652, -0.01770526,
          0.00456969, -0.03349583, -0.00796976, -0.00052356,
          0.00749602, -0.01419431],
        [ 0.02375025,  0.03779067, -0.04327583, -0.03690758,
         -0.03633132, -0.00770945,  0.04879537, -0.01035811,
         -0.0092103 , -0.00896599],
        [-0.01270083,  0.04556414, -0.02706355, -0.01993944,
         -0.00987042,  0.0399138 ,  0.02374915,  0.03437991,
         -0.02690615, -0.03061995],
        [-0.02449276,  0.02465619,  0.04457814, -0.0

In [22]:
embedded_docs[0].shape

(8,)